trigger:
  branches:
    include:
      - main

pool:
  name: default

stages:
- stage: terraformflow
  jobs:
  - job: terraform_job
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.6.6'
    - task: AzureCLI@2
      inputs:
         azureSubscription: 'MyServiceConnection01'
         scriptType: 'ps'
         scriptLocation: 'inlineScript'
         inlineScript: |
           terraform init `
                   -backend-config="storage_account_name=myrgst5679807578jhj" `
                   -backend-config="container_name=myrgccon" `
                   -backend-config="key=dev.terraform.tfstate" `
                   -backend-config="resource_group_name=MyRGc"
           
           terraform validate
           terraform fmt
           terraform plan